module.exports = {
    
"BookingCode" : { required: true, type: "string"},
"JourneyCode" : { required: false, type: "string"},
"Transporter_id" : { required: false, type: "int"},
"Driver_id" : { required: false, type: "int"},
"Truck_id " : { required: false, type: "int"},
"bt_hb_customer_id " : { required: false, type: "int"},
"Container_MTU_No" : { required: false, type: "string"},
"Container_Size" : { required: false, type: "string"},
"Location_From" : { required: false, type: "string"},
"Journey_Destination_Port " : { required: false, type: "string"},
"Booking_Journey_Type" : { required: false, type: "string"},
"Booking_Category" : { required: false, type: "string"},
"JourneyStartedDate" : { required: false, type: "date"},
"ExpectedDeliveryDate " : { required: false, type: "date"},
"LockBooking" : { required: false, type: "string"},
"TruckStayDuration" : { required: false, type: "string"},
"BookingStatus" : { required: false, type: "string"},
"CallCardAvatar " : { required: false, type: "string"},
"CallCardUploadedAt" : { required: false, type: "string"},
"BookingDate" : { required: false, type: "string"},
"BookingAmount" : { required: false, type: "string"},
"Tran_FullName " : { required: false, type: "string"},
"Dri_FullName" : { required: false, type: "string"},
"TruckName" : { required: false, type: "string"},
"TruckPlateNumber" : { required: false, type: "string"},
"TruckChasisNumber " : { required: false, type: "string"},
"TruckColor" : { required: false, type: "string"},
"TruckSize" : { required: false, type: "string"},
"CompanyName" : { required: false, type: "string"},
"LoggedIP" : { required: true, type: "string"},
"RecordCreatedAt" : { required: true, type: "date"},
"RecordUpdatedAt" : { required: false, type: "date"},
};

// allowed types - number, string, boolean, object, undefined
